"""add one time kalxa bridge tokens

Revision ID: 601eb0cbe9e8
Revises: 3e3efa0318b7
Create Date: 2026-09-12 20:32:49.530667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601eb0cbe9e8'
down_revision = '3e3efa0318b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kalxa_bridge_token_uses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bridge_id', sa.String(length=100), nullable=False),
    sa.Column('kalxa_organizer_id', sa.Integer(), nullable=False),
    sa.Column('kalxa_content_item_id', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kalxa_bridge_token_uses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kalxa_bridge_token_uses_bridge_id'), ['bridge_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_kalxa_bridge_token_uses_kalxa_content_item_id'), ['kalxa_content_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kalxa_bridge_token_uses_kalxa_organizer_id'), ['kalxa_organizer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kalxa_bridge_token_uses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kalxa_bridge_token_uses_kalxa_organizer_id'))
        batch_op.drop_index(batch_op.f('ix_kalxa_bridge_token_uses_kalxa_content_item_id'))
        batch_op.drop_index(batch_op.f('ix_kalxa_bridge_token_uses_bridge_id'))

    op.drop_table('kalxa_bridge_token_uses')
    # ### end Alembic commands ###
