"""initial ticketing tables

Revision ID: ddcc31c069c9
Revises: 
Create Date: 2026-09-12 11:33:25.685166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddcc31c069c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kalxa_content_item_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('organizer_name', sa.String(length=150), nullable=True),
    sa.Column('organizer_phone', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('ticket_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ticket_capacity', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_events_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_events_kalxa_content_item_id'), ['kalxa_content_item_id'], unique=False)

    op.create_table('ticket_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=150), nullable=False),
    sa.Column('customer_phone', sa.String(length=50), nullable=False),
    sa.Column('customer_email', sa.String(length=150), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('ticket_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_reference', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['ticket_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_orders_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_orders_payment_reference'), ['payment_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_ticket_orders_payment_status'), ['payment_status'], unique=False)

    op.create_table('entry_passes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('entry_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['ticket_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entry_passes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entry_passes_entry_code'), ['entry_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_entry_passes_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entry_passes_status'), ['status'], unique=False)

    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_pass_id', sa.Integer(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=False),
    sa.Column('checked_in_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['entry_pass_id'], ['entry_passes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkins_entry_pass_id'), ['entry_pass_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkins_entry_pass_id'))

    op.drop_table('checkins')
    with op.batch_alter_table('entry_passes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entry_passes_status'))
        batch_op.drop_index(batch_op.f('ix_entry_passes_order_id'))
        batch_op.drop_index(batch_op.f('ix_entry_passes_entry_code'))

    op.drop_table('entry_passes')
    with op.batch_alter_table('ticket_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_orders_payment_status'))
        batch_op.drop_index(batch_op.f('ix_ticket_orders_payment_reference'))
        batch_op.drop_index(batch_op.f('ix_ticket_orders_event_id'))

    op.drop_table('ticket_orders')
    with op.batch_alter_table('ticket_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_events_kalxa_content_item_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_events_active'))

    op.drop_table('ticket_events')
    # ### end Alembic commands ###
