"""add organizer banking details

Revision ID: e03295bc7029
Revises: ddcc31c069c9
Create Date: 2026-09-12 13:14:07.277072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e03295bc7029'
down_revision = 'ddcc31c069c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('account_holder', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('branch_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_instructions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_events', schema=None) as batch_op:
        batch_op.drop_column('payment_instructions')
        batch_op.drop_column('branch_code')
        batch_op.drop_column('account_number')
        batch_op.drop_column('account_holder')
        batch_op.drop_column('bank_name')

    # ### end Alembic commands ###
